# Generated by Django 3.1.14 on 2022-02-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_botusers'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='username',
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.botusers', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
