# Generated by Django 3.1.14 on 2022-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20220203_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
