# Generated by Django 3.1.14 on 2022-02-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customers_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='completed_orders_quantity',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество завершенных заказов'),
        ),
    ]
