# Generated by Django 3.1.14 on 2022-03-16 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220227_0732'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('coins_before', models.PositiveBigIntegerField(verbose_name='Монеты до')),
                ('coins', models.PositiveBigIntegerField(verbose_name='Монеты')),
                ('coins_after', models.PositiveBigIntegerField(verbose_name='Монетыпосле')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.botusers', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Вывод средств',
                'verbose_name_plural': 'Выводды средств',
            },
        ),
    ]
