# Generated by Django 3.1.14 on 2022-03-17 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orders_customer_telegram_id'),
        ('transactions', '0002_withdrawals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawals',
            options={'verbose_name': 'Вывод средств', 'verbose_name_plural': 'Выводы средств'},
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='coins',
            field=models.PositiveBigIntegerField(verbose_name='Сколько монет списалось'),
        ),
    ]
