# Generated by Django 3.1.14 on 2022-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_botusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='points',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество монет'),
        ),
    ]
