# Generated by Django 3.1.14 on 2022-02-12 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_botusers_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.botusers', verbose_name='Приведен пользователем'),
        ),
    ]
