# Generated by Django 3.1.14 on 2022-02-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='users_category',
            field=models.CharField(choices=[('customers', 'Заказчики'), ('workers', 'Исполнители')], default='customers', max_length=255, verbose_name='КАтегория пользователей'),
            preserve_default=False,
        ),
    ]
