# Generated by Django 3.1.14 on 2022-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220215_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botusers',
            old_name='points',
            new_name='coins',
        ),
    ]
