# Generated by Django 3.1.14 on 2022-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220227_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='coins',
            field=models.BigIntegerField(default=0, verbose_name='Количество монет'),
        ),
    ]
