# Generated by Django 3.1.14 on 2022-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220227_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='Уникальный номер')),
                ('referrals_quantity', models.PositiveBigIntegerField(verbose_name='Кол-во приведенных пользователей')),
            ],
            options={
                'verbose_name': 'Рекламная компания',
                'verbose_name_plural': 'Рекламные компании',
            },
        ),
    ]
