# Generated by Django 3.1.14 on 2022-04-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_advertisingcompanies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingcompanies',
            name='referrals_quantity',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Кол-во приведенных пользователей'),
        ),
    ]
