# Generated by Django 3.1.14 on 2022-02-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20220203_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='city',
            field=models.CharField(default='Неизвестный', max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Координаты'),
        ),
    ]
