# Generated by Django 3.1.14 on 2022-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20220207_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='completed_orders_quantity',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество выполненных заказов'),
        ),
        migrations.AddField(
            model_name='workers',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
