# Generated by Django 3.1.14 on 2022-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_botusers_points'),
        ('workers', '0004_auto_20220210_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='categories',
            field=models.ManyToManyField(to='main.JobCategories', verbose_name='Категории'),
        ),
    ]
