# Generated by Django 3.1.14 on 2022-02-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_workers_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerCategories',
        ),
    ]
