# Generated by Django 3.1.14 on 2022-03-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_workers_orders_at_longer_distance_access_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='max_distance',
            field=models.IntegerField(default=500, verbose_name='Максимальная дистанция для заказов'),
        ),
    ]
