# Generated by Django 3.1.14 on 2022-03-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_workers_max_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='max_distance',
            field=models.IntegerField(default=500, verbose_name='Максимальная дистанция для заказов в метрах'),
        ),
    ]
