# Generated by Django 3.1.14 on 2022-03-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_auto_20220307_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='telegram_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID в телеграмме'),
        ),
    ]
