# Generated by Django 3.1.14 on 2022-03-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_workers_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='telegram_id',
            field=models.CharField(default='', max_length=255, verbose_name='ID в телеграмме'),
        ),
    ]
