# Generated by Django 3.1.14 on 2022-02-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_botusers'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('customer_phone', models.CharField(max_length=255, verbose_name='Телефон заказчика')),
                ('customer_username', models.CharField(max_length=30, verbose_name='Юзернейм заказчика')),
                ('additional_contacts', models.CharField(max_length=255, verbose_name='Дополнительные контакты')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('execution_time', models.TimeField(verbose_name='Время выполнения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobcategories', verbose_name='Категория')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
