# Generated by Django 3.1.14 on 2022-02-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(default='asd', max_length=255, verbose_name='Имя для обращения к заказчику'),
            preserve_default=False,
        ),
    ]
