# Generated by Django 3.1.14 on 2022-02-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer_username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Юзернейм заказчика'),
        ),
    ]
