# Generated by Django 3.1.14 on 2022-02-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20220207_0640'),
        ('orders', '0002_ordercandidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.workers', verbose_name='Исполнитель'),
        ),
    ]
