# Generated by Django 3.1.14 on 2022-02-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220203_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='additional_contacts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительные контакты'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
