# Generated by Django 3.1.14 on 2022-02-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_voice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Ожидает начала', max_length=20, verbose_name='Статус'),
        ),
    ]
