# Generated by Django 3.1.14 on 2022-02-15 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220214_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersTimestamps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.PositiveBigIntegerField(verbose_name='Секунды')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Временная отметка для заказа',
                'verbose_name_plural': 'Пременные отметки для заказов',
            },
        ),
    ]
