# Generated by Django 3.1.14 on 2022-02-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_delete_workercategories'),
        ('orders', '0007_orderstimestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='candidates',
            field=models.ManyToManyField(related_name='order_candidates', to='workers.Workers', verbose_name='Кандидаты'),
        ),
    ]
