# Generated by Django 3.1.14 on 2022-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220220_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstimestamps',
            options={'verbose_name': 'Временная отметка для заказа', 'verbose_name_plural': 'Временные отметки для заказов'},
        ),
    ]
