# Generated by Django 3.1.14 on 2022-03-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220227_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Ожидает оплаты', max_length=120, verbose_name='Статус'),
        ),
    ]
